# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: auth-ingress
# spec:
#   rules:
#   - host: auth.server1
#     http:
#       paths:
#       - backend:
#           serviceName: service-auth
#           servicePort: 8031