---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-proxy
  namespace: kong
spec:
  ports:
    - name: proxy
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: proxy-ssl
      port: 443
      protocol: TCP
      targetPort: 8443
    # - name: proxy-admin
    #   port: 8001
    #   protocol: TCP
    #   targetPort: 8001
    # - name: status
    #   port: 8100
    #   protocol: TCP
    #   targetPort: 8100
    # - name: proxy-admin-ssl
    #   port: 444
    #   protocol: TCP
    #   targetPort: 8444
    # - name: gui-admin
    #   port: 8002
    #   protocol: TCP
    #   targetPort: 8002
  selector:
    app: ingress-kong
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-admin
  namespace: kong
spec:
  ports:
    - name: proxy
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: proxy-ssl
      port: 444
      protocol: TCP
      targetPort: 8444
  selector:
    app: ingress-kong
