apiVersion: v1
kind: Service
metadata:
  name: svc-db-kong
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database-kong
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-kong
  labels:
    type: local-2
spec:
  storageClassName: postgres-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-kong
spec:
  storageClassName: postgres-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      name: database-kong
  template:
    metadata:
      labels:
        name: database-kong
    spec:
      containers:
        - name: c-db-postgres
          image: postgres:9.6
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: task-pv-storage-kong
          env:
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong

      volumes:
        - name: task-pv-storage-kong
          persistentVolumeClaim:
            claimName: task-pv-claim-kong
