apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-kong
  namespace: kong
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-migrations
          image: kong:2.4
          command:
            - "/bin/sh"
            - "-c"
            - "while true; do kong migrations list; if [[ 0 -eq $? ]]; then exit 0; fi; sleep 2;  done;"
          env:
            - name: KONG_PG_HOST
              value: postgres
            - name: KONG_PG_PASSWORD
              value: kong
      containers:
        - name: proxy
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: postgres
            - name: KONG_PG_PASSWORD
              value: kong
            - name: KONG_PLUGINS
              value: bundled,custom-auth
            - name: KONG_LUA_PACKAGE_PATH
              value: "/opt/?.lua;;"
          volumeMounts:
            - name: kong-plugin-custom-auth
              mountPath: /opt/kong/plugins/custom-auth
      volumes:
        - name: kong-plugin-custom-auth
          configMap:
            name: kong-plugin-custom-auth
